AlwaysShowRadius: 8
RaycastRadius: 48
SearchRadius: 52
MoreChecks: false #This will enable more raycasts per mob, increasing performance hit but showing partially visible mobs
OccludePlayers: false #Enabling this will make the plugin cull hidden players alongside entities
RecheckInterval: 20 #Time in ticks between rechecking visible mobs