AlwaysShowRadius: 8
RaycastRadius: 48
SearchRadius: 48
EngineMode: 3
CullPlayers: false #Enabling this will make the plugin cull hidden players alongside entities
OnlyCullSneakingPlayers: false #This feature will be fully implemented in 1.4.0. Enabling this will make the plugin only cull hidden players that are sneaking. Note that CullPlayers must also be true.
RecheckInterval: 20 #Time in ticks between rechecking visible mobs

BlockDataManager:
  ExpireAfterTicks: 2400
  CleanupInterval: 1200